### ISSUE TITLE
Mismatch between keys `cloudInit` and `userData.cloud-init` in `scaleway.InstanceServer`

### ISSUE THREAD

**Issue by arjun-1** [lbrlabs/pulumi-scaleway#114]
When creating an `InstanceServer` provided with the `cloudInit` key, any subsequent invocation of `pulumi up` will incorrectly trigger an update of this resource as the field `userData.cloud-init` is present in the created state, but absent in the resource description of `InstanceServer`.

When (by incorrectly using the API) passing the cloud-init configuration as `userData: { 'cloud-init': ... }`, pulumi no longer wishes to update the resource.

This might be [fixed upstream](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/instance_server#with-user-data-and-cloud-init), where `cloud-init` is passed as a key to `userData`. It coincides with the [migration](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/migration_guide_v2#instance) from V1 to V2 of the Scaleway API.

EDIT: just passing `'cloud-init'` as a key to `userData` fixes the problem

**Comment by jaxxstorm** [comment]
We're up to date with the latest upstream now, so I believe this is resolved.
