### ISSUE TITLE
Beta resource

### ISSUE THREAD

**Issue by danquah** [lbrlabs/pulumi-scaleway#147]
I'm looking into using some beta-resources from Scaleway. But, when I tried to create eg. an [IAM Group](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/iam_group) i could not find it in the Pulumi provider.

The reason seems to be that the Terraform provider will enable beta resources [conditionally](https://github.com/Codelax/terraform-provider-scaleway/blob/master/scaleway/provider.go#L30) depending on an [environment variable](https://github.com/scaleway/scaleway-sdk-go/blob/master/scw/env.go#L24).

A `make provider` with the following modification to the `Makefile`

```Makefile

...

WORKING_DIR     := $(shell pwd)

# Enable beta resources.
export SCW_ENABLE_BETA := true
```

Produces output that seems to indicate the resources are now available.

What are the attitude towards having the Pulumi provider include beta resources? And is it simple enough that a PR would be accepted (I might need some pointers) or does it require more insight into how this project it set up?

**Comment by danquah** [comment]
I've implemented the modifications described above to a fork https://github.com/danquah/pulumi-scaleway/pull/1

I'd be happy to make an actual PR with those changes (would be nice with an upgrade to 2.5.0 before the PR as it has more of the IAM resources)

**Comment by jaxxstorm** [comment]
I don't intend to add beta resources to the GA builds of the provider. I'll consider adding the env var to prerelease versions

**Comment by danquah** [comment]
That fair, I totally get that you want to avoid blurring the lines between whats GA and whats not.

I'm curious. Do you know how other providers are handling things like this? Eg. lets say Scaleway had an official provider - I would expect they also wanted a clear separation between what is GA and whats not.

One way would be to have a whole extra type ala 

```typescript
import * as scaleway from "@pulumiverse/scaleway-beta";
```

Another approach would to have a runtime variable that prevented a specific resource to be used - but that would not keep you from using the resource in your programs which again would be unfortunate.

Do you know what other people are doing?

**Comment by jaxxstorm** [comment]
I personally haven't seen this pattern in any other bridged provider. In tf, you only have to generate a new binary, but for Pulumi you also have to generate the libraries too.

I think it'd be reasonable to fork this provider and call it "scaleway-beta"

**Comment by danquah** [comment]
Good point about the libraries. It makes things a bit more messy.

Re the fork - wonder if it would be possible to source both providers from the same repository 🤔 

Don't know if you have any contacts at Scaleway, but I'll just try and reach out and ask the whether this beta-pattern is something they expect to use going forward. If this is a one-off thing for the IAM resources it does not make much sense to put any energy into it. But, if we're going to have a new set of beta resources again and again, it might merit some extra work.

In the end, if we're going to need the IAM resources on the project I'm currently working on I would probably have some time to put in to making this work. If IAM all of the sudden goes GA, my problem goes away - so lets see :)

**Comment by danquah** [comment]
[slack link](https://scaleway-community.slack.com/archives/C015RD31DNK/p1667550479246899) for reference (it's going to expire i 90 days)

**Comment by danquah** [comment]
A couple of quotes from Slack, we should of cause be aware that this is just a quick dialog and nothing binding:
> (Me): Does anyone know if the the pattern where you specify  SCW_ENABLE_BETA to enable beta-resources is something that will be used going forward, or whether it is mostly just used for IAM for now?  ...
> (Scaleway representative): It is mostly used for IAM, we are adding other beta products but we do not set them behind SCW_ENABLE_BETA variable. Iam is a specific case
> (Me): OK - so it might actually not be worth the work to introduce anything special for SCW_ENABLE_BETA as things stands right now? I understand things might change in the future :)
> (Scaleway representative): Yes, I don't think it would be worth the work, we want to avoid using SCW_ENABLE_BETA, it could be removed after iam GA.

So two takeaways:

1. No point in doing any more work re. SCW_ENABLE_BETA
1. That being said, the Terraform provider can at any point contain non-GA resources regardless of any flag like SCW_ENABLE_BETA. It might be a good idéa to mention this somewhere to the users of the provider. Ie. you should always verify with Scaleway whether the resources you use are GA or not.

I think this issue is pretty much resolved.

**Comment by danquah** [comment]
Version 2.8.0 of the terraform provider has now [enabled IAM](https://github.com/scaleway/terraform-provider-scaleway/releases/tag/v2.8.0), so I guess we'll have it available with the next update of the Pulumi provider. With the feedback I got from their Slack channel it sound like they won't repeat this pattern for future features, so I'm closing this issue.
