### ISSUE TITLE
Enhancement Request - Include Access Key and Secret Key in scaleway.objectBucket Output

### ISSUE THREAD

**Issue by ayoub3bidi** [lbrlabs/pulumi-scaleway#257]
### Current Behavior:

The `scaleway.objectBucket` resource currently returns only the endpoint in its output.

### Enhancement Proposal:

Include the Access Key and Secret Key in the pulumi output of the scaleway.objectBucket resource.

### Justification:

* Developer Convenience: Having direct access to the Access Key and Secret Key in the output would streamline the dev experience.

* Automation and Integration: Simplifies automation and integration with other tools, eliminating the need for additional steps to programmatically fetch these credentials.

* Reduced Configuration Overhead: Developers can more easily manage and configure their applications without separately retrieving these sensitive credentials.

**Comment by ayoub3bidi** [comment]
Thanks ❤️ I hope the access and secret keys will be added soon to the output instead of playing with `IamApiKey`. for a better dev experience

**Comment by jaxxstorm** [comment]
This provider bridges the upstream terraform provider. Please file this issue at https://github.com/scaleway/terraform-provider-scaleway and it'll be picked up when it's implemented there
